language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# faster builds on new travis setup not using sudo
sudo: false
addons:
  apt:
    packages:
      - beanstalkd
install:
  - '[[ -z "$CI_USER_TOKEN" ]] || composer config github-oauth.github.com ${CI_USER_TOKEN};'
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - php ./vendor/bin/codecept run
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then php ./vendor/bin/codecept run --coverage-xml; fi
after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi
